### ISSUE TITLE
RKI 改了一点版

### ISSUE THREAD

**Issue by cmp0xff** [covid19-eu-zh/covid19-eu-data#1]
https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Fallzahlen.html
加了死亡人数这一栏
且 21:30 又一次更新

**Comment by emptymalei** [comment]
Fixed
https://github.com/covid19-eu-zh/covid19-eu-data/blob/a3b8854c69e805318620c827ca221e10f39f7fe5/scripts/download_de.py#L63
