### ISSUE TITLE
IT

### ISSUE THREAD

**Issue by gena** [covid19-eu-zh/covid19-eu-data#19]
I've added a simple implementation to pull IT data, I did too many changes in my fork to do a PR, but you can integrate it from here: https://github.com/gena/covid19-eu-data/blob/master/scripts/download_it.py. It simply pulls the data from another repo, but it's handy to have all data in one place.

**Comment by emptymalei** [comment]
Hi @gena 

Thanks for the new issue.

We didn't include IT in the beginning because it is already well maintained data on GitHub. 

> but it's handy to have all data in one place.

That makes sense. We will add IT on the next change. And thank you for your script! 😃
