### ISSUE TITLE
dataset/covid-19-fr.csv数据错误

### ISSUE THREAD

**Issue by RCZhao** [covid19-eu-zh/covid19-eu-data#2]
csv文件中第9行与第31行数据有误，对应 authority 显示为 sum，似乎应该是某大区的数据？

**Comment by emptymalei** [comment]
大概分别是海岛和城市数据。
- [x] 暂时保留原始数据。
- [ ] 计算正确的总数

Fixed
https://github.com/covid19-eu-zh/covid19-eu-data/blob/5799b19fd99c7b1f81a3cb84106b06df5ae4e5d3/scripts/download_fr.py#L66
