### ISSUE TITLE
For Netherlands: country level death and hospitalization numbers?

### ISSUE THREAD

**Issue by elvissey1984** [covid19-eu-zh/covid19-eu-data#36]
Given that city numbers are not complete in the sense that they don't add up to the national total, and that no deaths/hospitalizations are reported on the city level, and that given the low test rate, deaths and hospitalizations are likely to be more meaningful than the confirmed cases #, perhaps it is a good idea to add national numbers which can be found at https://www.rivm.nl/nieuws/actuele-informatie-over-coronavirus.

**Comment by emptymalei** [comment]
Indeed. Also, the cases on the country level are inconsistent with ECDC data. 
https://github.com/covid19-eu-zh/covid19-eu-data/blob/master/dataset/covid-19-ecdc.csv

Will add this soon.

**Comment by emptymalei** [comment]
We are tracking the total cases for NL now.

https://github.com/covid19-eu-zh/covid19-eu-data/blob/b7d1c614f62e588869a5c0785bb74061767ed00b/scripts/download_nl.py#L74-L101

https://github.com/covid19-eu-zh/covid19-eu-data/blob/b7d1c614f62e588869a5c0785bb74061767ed00b/dataset/daily/nl/nl_covid19_2020-03-26_14_00.csv#L357
