### ISSUE TITLE
Wales' cases is the string 'cases' in some files

### ISSUE THREAD

**Issue by edgarrmondragon** [covid19-eu-zh/covid19-eu-data#38]
Hello everyone,

I found that some files for daily Wales data have a row where the column `cases` has the value `"cases"`:

- [dataset/daily/wales/wales_covid19_2020-03-25_12_00.csv][file-1]
- [dataset/daily/wales/wales_covid19_2020-03-26_12_00.csv][file-2]

[file-1]: https://github.com/covid19-eu-zh/covid19-eu-data/blob/master/dataset/daily/wales/wales_covid19_2020-03-25_12_00.csv
[file-2]: https://github.com/covid19-eu-zh/covid19-eu-data/blob/master/dataset/daily/wales/wales_covid19_2020-03-26_12_00.csv

**Comment by emptymalei** [comment]
This should be fixed in #39
