### ISSUE TITLE
AT bug with "healed" persons

### ISSUE THREAD

**Issue by SeaLife** [covid19-eu-zh/covid19-eu-data#4]
Hey,

the healed persons in AT are counted/added as "cases" and creates wrong data..

This dataset is Tirol:
```
[2, 2, 3, 4, 4, 7, 7, 8, 8, 8, 9, 16, 27, 2, 32, 2, 37, 2, 57, 2, 81, 2, 109]
```

(You may see the issue... 27, 2, 32, 2, 37, 2 - the 2 is probably the healed person count)

Regards
SeaLife

**Comment by emptymalei** [comment]
Hi @SeaLife 

Thanks for reporting the bug. It is now fixed. 

We also started tracking deaths and recovered in AT.

https://github.com/covid19-eu-zh/covid19-eu-data/blob/73fc5d80cece194a1efacc4a3e26978b156061e7/scripts/download_at.py#L55-L64

We will close the issue for now. If there's anything else to be communicated, feel free to reopen it.
