### ISSUE TITLE
HTML files in ./cache/daily/ sub folders are invalid for Windows Users

### ISSUE THREAD

**Issue by sbgalloway** [covid19-eu-zh/covid19-eu-data#43]
Files in Windows cannot contain any of the following characters: 
\ / : * ? " < > |

Because of this is, Windows users will get this error while trying to clone the repo:
`error: invalid path 'cache/daily/at/2020-03-25T15:00:00.html'`

Is this something that can be fixed?

**Comment by emptymalei** [comment]
ah yes, that can be fixed.

Added to todo: https://github.com/orgs/covid19-eu-zh/projects/1#card-35403120

**Comment by emptymalei** [comment]
fixed
