### ISSUE TITLE
County data

### ISSUE THREAD

**Issue by WhoIAmm** [covid19-eu-zh/covid19-eu-data#44]
Could you please provide county data, that would be very grateful！

**Comment by emptymalei** [comment]
ECDC provides data on country level:
https://github.com/covid19-eu-zh/covid19-eu-data/blob/master/dataset/covid-19-ecdc.csv

If you need data for countries outside of EU, the JHU repo has a better coverage.
https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data

**Comment by emptymalei** [comment]
@WhoIAmm We are closing this issue. If you have further questions, feel free to reopen it. 😄
