### ISSUE TITLE
DE RKI data by district -- help on how to map between districts and nuts_3

### ISSUE THREAD

**Issue by averissimo** [covid19-eu-zh/covid19-eu-data#45]
I've implemented in R a function to download the data (see [download.state()](https://github.com/averissimo/covid19-de_rki-data/blob/master/R/download.R#L136) and [download.raw()](https://github.com/averissimo/covid19-de_rki-data/blob/master/R/download.R#L197))

However, I cannot find a reasonable way to map between districts *(IdLandkreise)* and nuts_3

If anyone knows how to do it I'll convert the code to python to be included here.

**Comment by emptymalei** [comment]
Are you using the following dataset for DE?

https://www.arcgis.com/home/item.html?id=dd4580c810204019a7b8eb3e0b329dd6&view=list#data

> However, I cannot find a reasonable way to map between districts (IdLandkreise) and nuts_3

I am not sure what this means. According to [Wikipedia](https://en.wikipedia.org/wiki/NUTS_statistical_regions_of_Germany), NUTS3 in Germany is a district. I think one can find the Landkreis names and ids in the above table.

> If anyone knows how to do it I'll convert the code to python to be included here.

I am not familiar with R but I think we can set up R workflows here too. 😄 GitHub Actions supports a full matrix of platforms (Linux, Windows, Mac) and we can choose one and install R.

**Comment by averissimo** [comment]
Yes that's the data origin *(the Id is not the same as I'm going directly at the Feature Server)*

```
  # build url for query
  url.base <- 'https://services7.arcgis.com'
  url.key  <- 'mOBPykOjAyBO2ZKk'
  url.path <- 'arcgis/rest/services/RKI_COVID19/FeatureServer/0/query'
```

I'm not very familiar with arcgis, but that's why the difference in the ID

> I am not sure what this means. According to Wikipedia, NUTS3 in Germany is a district. I think one can find the Landkreis names and ids in the above table.

I have a sheet trying to map them manually  by string. But it's a work in progress with some challenging matches -- [link to google sheets](https://docs.google.com/spreadsheets/d/1dsZOE94oVghsy1pUIbQEK7pBa58kEc4-HieRcXyvwCI/edit?usp=sharing) *(red cells are the ones missing a match)*

> I am not familiar with R but I think we can set up R workflows here too. smile GitHub Actions supports a full matrix of platforms (Linux, Windows, Mac) and we can choose one and install R.

I'm using a cronjob to check how good the code on building a consistent dataset over the updates, as the full dataset is updated daily *(new unique ids)* with some partial updates that are incremental *(using same ids during 24h period)*.

**Comment by emptymalei** [comment]
Now I understand the problem.

Do you think [this table](https://www.arcgis.com/home/item.html?id=917fc37a709542548cc3be077a786c17&view=list#data) helps? It has NUTS code, name, and the landkreis id.


![Screen Shot 2020-04-02 at 14 58 19](https://user-images.githubusercontent.com/663798/78252084-97729d00-74f2-11ea-8fd1-3d8ab7035022.png)


For example, in your spreadsheet, you are still looking for the match of `SK Frankenthal`. We can find the name is `Frankenthal (Pfalz)` in [the table](https://www.arcgis.com/home/item.html?id=917fc37a709542548cc3be077a786c17&view=list#data).

![Screen Shot 2020-04-02 at 15 04 39](https://user-images.githubusercontent.com/663798/78252777-a9a10b00-74f3-11ea-8e47-3d184f36920a.png)

**Comment by averissimo** [comment]
<3 I spent hours looking for that. I knew it was a good idea to post here!

Thanks!

**Comment by averissimo** [comment]
Done!

Data is available as [csv](https://github.com/averissimo/covid19-de_rki-data/blob/master/data/rki.covid19.csv) *(updated every ~8 hours)* and the function to retrieve data works as expected.

Let me know how to proceed with integration here. Functional R code to retrieve data would be as following:

```
install.packages('BiocManager')
BiocManager::install('averissimo/covid19-de_rki-data')

library('rki.de.district.data')

new.data <- rki.de.district.data::update_dataset()
```

It has the following structure

![image](https://user-images.githubusercontent.com/211358/78269562-0dcec980-750a-11ea-8d17-c6f6e1b91986.png)

**Comment by emptymalei** [comment]
Nice work! This is a very nice dataset.

If you don't mind, we can pull your [csv file](https://github.com/averissimo/covid19-de_rki-data/blob/master/data/rki.covid19.csv) into our repo and replace our [`covid-19-de.csv` file](https://github.com/covid19-eu-zh/covid19-eu-data/blob/master/dataset/covid-19-de.csv). 

We will have to do a few transformations.

- [ ] Group by the geolocations and dates to get the sum. `age.group` and `gender` doesn't seem to fit into the current format. We will add a link to your repo so that people can always refer to the full dataset if needed.
- [ ] Rename the columns a bit and also generate daily files to make sure it is consistent with the previous data.
- [ ] Generate daily files. We have the data for each day (datetime) in `dataset/daily` folder.

**Comment by averissimo** [comment]
I'm looking deeper at the data and it doesn't have the same quality as the current source at least in terms of deaths.

Seems like RKI obfuscated the data in some way so that it shouldn't be used as time series.

**Comment by emptymalei** [comment]
Hmm it seems that RKI has a strange process. :P
