### ISSUE TITLE
NL data are bad after March 31

### ISSUE THREAD

**Issue by gena** [covid19-eu-zh/covid19-eu-data#46]
File format change?

![image](https://user-images.githubusercontent.com/169821/78173808-90974c00-7458-11ea-8bf7-a798b7e7490f.png)

**Comment by emptymalei** [comment]
Ah I see. They have stopped reporting cases in the table. Instead, the table contains hospitalized patients.

![Screen Shot 2020-04-01 at 22 29 27](https://user-images.githubusercontent.com/663798/78183497-48802580-7468-11ea-9bad-16fe5f777ad9.png)

Well, that being said, we can still track NL but there will be no `cases` columns.

**Comment by emptymalei** [comment]
We have implemented a temporary fix in https://github.com/covid19-eu-zh/covid19-eu-data/commit/a40ae201d1244567051925936d955275c228662a

The cases columns starting from 0331 is being kept empty.

However, there are new data sources listed on the official website: https://github.com/orgs/covid19-eu-zh/projects/1#card-35684892
We might switch over to these new data sources later.

**Comment by gena** [comment]
They've started publishing it again

**Comment by emptymalei** [comment]
Yep. Here we go.
https://github.com/covid19-eu-zh/covid19-eu-data/blob/master/dataset/daily/nl/nl_covid19_2020-04-09_13_50.csv
