### ISSUE TITLE
Fix date format to ISO date

### ISSUE THREAD

**Issue by hyperknot** [covid19-eu-zh/covid19-eu-data#47]
Hi and thanks for this great effort. There is one very confusing issue with your data, is that it's using a date format which is almost exactly like ISO dates, but it has the months and days swapped.

This is an extremely confusing date format if on purpose, or simply a bug if not.

The right ISO 8601 format can be found on Wikipedia: https://en.wikipedia.org/wiki/ISO_8601

It looks like this: `2020-04-13T00:55`

**Comment by emptymalei** [comment]
Hi @hyperknot 
Thanks for reporting this bug. AFAIK, this only happened in the HU data.
In EU, most of the countries use day-first format. So I assumed that HU will also use day-first format too. Obviously they don't.
The bug has been fixed. 😄

**Comment by hyperknot** [comment]
Thanks for the answer and for the fix! You are right, I've only checked Hungary! Good to know it's fixed.
