### ISSUE TITLE
Netherland Cities Encoding Issue

### ISSUE THREAD

**Issue by erlange** [covid19-eu-zh/covid19-eu-data#49]
Some data should be merged for:

- Noardeast-Fryslân
- Noardeast-FryslÃ¢n

and:

- SÃºdwest-FryslÃ¢n
- Súdwest Fryslân
- Súdwest-Fryslân

Cheers,

**Comment by emptymalei** [comment]
Hi @erlange ,

Thank you for spotting this issue. It is very valuable. We have now implemented a fix for these geolocations.

https://github.com/covid19-eu-zh/covid19-eu-data/commit/1b6e45bbb22fc9f4954c6ade0ead9f6407f23d3f#diff-77308b6ac3a1ca045f2b3d41298c40fe

**Comment by erlange** [comment]
Thanks for your quick response
