### ISSUE TITLE
Netherlands cities should merge

### ISSUE THREAD

**Issue by erlange** [covid19-eu-zh/covid19-eu-data#54]
Hello again,
I believe these Netherlands cities should merge, don't know which one is correct though:
```
's-Gravenhage
```
 and 
```
s-Gravenhage
```

Cheers

**Comment by emptymalei** [comment]
I believe the first one is more official according to wikipedia.

Now fixed in the code. The data will be updated in a few min.

https://github.com/covid19-eu-zh/covid19-eu-data/blob/a91fd334717638c3acdf578b77a49d175b394104/scripts/download_nl.py#L228
