### ISSUE TITLE
Metadata Update

### ISSUE THREAD

**Issue by reeshmabijosh** [covid19-eu-zh/covid19-eu-data#59]
Hello,
Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse as a piece of common COVID-19 data frame   https://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/YWVN3B
Would you be willing to help with the maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for the medical science community.

**Comment by emptymalei** [comment]
Hi @reeshmabijosh 
Thanks. Sure, would love to make it easier to access by maintaining the metadata. 
We currently have a set of metadata in the repo in YAML format.  

I had a look at the dataverse guides and didn't find any detailed information about how the metadata is represented (datapackages.json or any other formats).
Would be grateful if you enlighten me on how to provide the metadata.

Thanks.

**Comment by reeshmabijosh** [comment]
Hello,

Thanks for your willingness to contribute.
 Please register in CoronaWhy Dataverse https://datasets.coronawhy.org/ and
you will get the necessary permissions for editing your dataset.
Then please add relevant metadata - description and keywords to your
dataset.
This is an example of a dataset with good metadata
https://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/TZMOTL


Thanks
Reeshma K

**Comment by emptymalei** [comment]
@reeshmabijosh hmm it doesn't allow me to edit it.

**Comment by k-goncharova** [comment]
Hello @emptymalei, as soon as you register in CoronaWhy Dataverse https://datasets.coronawhy.org/ and you will get all the necessary permissions for editing your dataset.

**Comment by emptymalei** [comment]
@k-goncharova I have registered. The screenshot I made in the previous reply is one that after I login.

**Comment by k-goncharova** [comment]
@emptymalei could you please give me your name as you registered? I'll give the permissions.

**Comment by emptymalei** [comment]
@k-goncharova Sure. username: `leima137`

Thanks!

**Comment by k-goncharova** [comment]
@emptymalei thank you! I've just granted the necessary permissions. Please let know if any questions during the update process.

**Comment by emptymalei** [comment]
@k-goncharova Thank you for the help. I confirm that I can edit the metadata now. 😄
