### ISSUE TITLE
Poland: wrong date starting on 2021-02-03

### ISSUE THREAD

**Issue by jop22** [covid19-eu-zh/covid19-eu-data#61]
Starting on 2021-02-03 day and month are messed up in dataset/covid-19-pl.csv and daily/pl/ . So for example 2021-03-02 instead of 2021-02-03.
Additionally there is no data for 2021-02-01.

**Comment by emptymalei** [comment]
It should have been fixed now. The reason was the day-first or month-first date format confusion.

2021-01-02 was overwritten by 2021-02-01 due to this confusion. Luckily we have git history so I have pulled the data back from the commit history.

Thanks! 😄

**Comment by jop22** [comment]
Thanks for fixing!

I have bad news - link used in downloading data for Poland stopped working on 2021-02-12. :(
Current data are now available under:
https://arcgis.com/sharing/rest/content/items/a8c562ead9c54e13a135b02e0d875ffb/data

1 month archive:
https://arcgis.com/sharing/rest/content/items/153a138859bb4c418156642b5b74925b/data

(Both links taken from: https://wojewodztwa-rcb-gis.hub.arcgis.com/pages/dane-do-pobrania)
I don't know the link providing metadata.

Knowing data provider nobody can guarantee that new links will work forever (or at least until pandemic is over). :(

**Comment by emptymalei** [comment]
@jop22 
Thank you for providing the links. I'll migrate the scripts ASAP. The new data quality looks good. 😸

**Comment by emptymalei** [comment]
@jop22 We now take data from the monthly archive. The daily data for the past few days are backfilled.

Thank you for spotting the issues and providing the data sources.
